version: "2"
services:
  netatalk:
    image: cptactionhank/netatalk:latest
    container_name: netatalk
    restart: always
    network_mode: "host"
    environment:
      - AVAHI=1
      - AFP_USER=${LOGIN}
      - AFP_PASSWORD=${PASSWORD}  
    volumes:
      - ${TIMEMACHINE}:/media/timemachine
      - ${SHARE}:/media/share
      - ./afp.conf:/etc/afp.conf




